{{- if not (hasKey $.Values.graphdb.workers.persistence "volumeClaimTemplateSpec") }}
{{- $storageClassName := $.Values.graphdb.workers.persistence.storageClassName | default $.Values.global.storageClass }}
{{- if or (ne $storageClassName "standard") (ne $storageClassName "") }}
{{- if ne .Values.graphdb.topology "standalone" }}
{{- if eq .Values.graphdb.workers.persistence.volumeNamePrefix "graphdb-default-worker" }}
{{- range $i, $worker_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.workersCount | int ) 1 }}
#
# Default persistence volume for GraphDB workers. Data is stored on the node file system. Suitable
# for Minikube deployments.
#
# Note: Not to be used in production or multi node cluster.
#
---
apiVersion: {{ $.Values.versions.pv }}
kind: PersistentVolume
metadata:
  name: {{ $.Release.Namespace }}-graphdb-default-worker-{{ $worker_index }}-pv
  labels:
    name: {{ $.Release.Namespace }}-graphdb-default-worker-{{ $worker_index }}-pv
spec:
  claimRef:
    name: graphdb-worker-{{ $worker_index }}-data-dynamic-pvc-graphdb-worker-{{ $worker_index }}-0
    namespace: {{ $.Release.Namespace }}
  storageClassName: {{ $storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $.Values.graphdb.workers.persistence.storage }}
  hostPath:
    path: {{ $.Values.deployment.storage }}/graphdb-worker-{{ $worker_index }}-data

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
